env: "local"
pg_connection_string: "postgresql://127.0.0.1:5432/postgres?user=postgres&password=changeme&sslmode=disable"
http_server:
  port: "8080"
  timeout: 4s
  idle_timeout: 30s
auth:
  access_token_secret: "secret"  
  refresh_token_secret: "secret"  
