env: "local" # local, dev или prod
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
mongo:
  host: "my-mongodb"
  port: "27017"
  username: "admin"
  password: "admin"
  database: "test"
  collection: "link"
